=== uo295526/SEW2/xml/circuito.dtd
<!ELEMENT circuitos (circuito)>
<!ELEMENT circuito (nombre, longitud, anchura, fechaInicio, horaInicio, numeroVueltas, localidad, pais, referencias, fotografias, videos, coordenadas, puntosTramos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT anchura (#PCDATA)>
<!ELEMENT fechaInicio (#PCDATA)>
<!ELEMENT horaInicio (#PCDATA)>
<!ELEMENT numeroVueltas (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT referencias (referencia)+>
<!ELEMENT referencia (enlace)>
<!ELEMENT fotografias (fotografia)+>
<!ELEMENT videos (video)+>
<!ELEMENT fotografia (enlace)>
<!ELEMENT video (enlace)>
<!ELEMENT enlace (#PCDATA)>

<!ELEMENT coordenadas (longitud, latitud, altitud)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>

<!ELEMENT puntosTramos (tramoActual)+>
<!ELEMENT tramoActual (distancia, puntoFinal, numSector)>
<!ELEMENT distancia (#PCDATA)>
<!ELEMENT puntoFinal (#PCDATA)>
<!ELEMENT numSector (#PCDATA)>

=== uo295526/SEW2/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">

<!--mirar de meter atributos (con unidades, como metros)-->
<circuitos>

<circuito>
<nombre>Zandvoort</nombre>
<longitud>4'259 km</longitud>
<anchura>X km</anchura>
<fechaInicio>23 de agosto</fechaInicio>
<horaInicio>12:00 am</horaInicio>
<numeroVueltas>72</numeroVueltas>
<localidad>Holanda Septentrional</localidad>
<pais>Paises Bajos</pais>
<referencias>
    <referencia>
        <enlace>https://www.dazn.com/es-ES/news/motor/circuito-zandvoort-donde-esta-como-es-caracteristicas-como-llegar-fotos-escenario-gp-paises-bajos-mundial-f1/z4tfep6uuudo1fqpzfnrzconu</enlace>
    </referencia>
    <referencia>
        <enlace>https://www.statsf1.com/es/circuit-zandvoort.aspx</enlace>
    </referencia>
    <referencia>
        <enlace>https://www.redbull.com/pe-es/f1-circuito-zandvoort-lo-que-debes-saber</enlace>
    </referencia>
</referencias>
<fotografias>
    <fotografia>
        <enlace>fotoCircuito.PNG</enlace>
    </fotografia>
</fotografias>
<coordenadas>
    <longitud>52.388292</longitud>
    <latitud>4.543011</latitud>
    <altitud>0,3048 (revisar estos tres)</altitud>
</coordenadas>
<puntosTramos>
    <tramoActual>
        <distancia>a</distancia>
        <puntoFinal>b</puntoFinal>
        <numSector>c</numSector>
    </tramoActual>
    <tramoActual>
        <distancia>d</distancia>
        <puntoFinal>e</puntoFinal>
        <numSector>f</numSector>
    </tramoActual>
</puntosTramos>


</circuito>

</circuitos>
